spring.security.user.name=admin
spring.security.user.password=admin

# Active Spring Profile (default to uat, override with --spring.profiles.active=prod in prod)
#spring.profiles.active=uat

server.servlet.context-path=/api

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Database Configuration
spring.datasource.url=jdbc:mysql://150.241.244.131:3306/merchant_management_system_prod?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=merchant
spring.datasource.password=merchant@12345

# Server Configuration (Runs on port 8080 behind reverse proxy)
server.port=8080
server.ssl.enabled=false

# CORS Allowed Origin
app.cors.allowed-origin=https://portal.utsabpay.com

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Connection Pool Configuration
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000


#JWT
jwt.secret=ou2+FqtcAaUpXJy07OXNvhhAVY5Qa9E32qfnnlSafp4=
jwt.expiration=1800000


# Logging Configuration
logging.level.com.project2.ism=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Kolkata

# Validation Configuration
#spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true

## Actuator Configuration (Optional for health checks)
#management.endpoints.web.exposure.include=health,info
#management.endpoint.health.show-details=when-authorized

# Application Configuration
app.name=ISM Product Management System
app.version=1.0.0


# Max file size per file
spring.servlet.multipart.max-file-size=15MB

# Max total request size (sum of all files in request)
spring.servlet.multipart.max-request-size=20MB

# GoDaddy SMTP Configuration
spring.mail.host=smtpout.secureserver.net
spring.mail.port=587

spring.mail.username=noreply@utsabpay.com
spring.mail.password=Password@1998

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtpout.secureserver.net

#spring.mail.properties.mail.smtp.timeout=10000
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG

surepass.api.token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4MTg1NDgwNiwianRpIjoiNmRmNjQ3ZWItZDUzYy00NWU5LWJkNDEtYmY3MDNkZDUwNTVlIiwidHlwZSI6ImFjY2VzcyIsImlkZW50aXR5IjoiZGV2LnNhbXJ0Y3JlZGl0QHN1cmVwYXNzLmlvIiwibmJmIjoxNzgxODU0ODA2LCJleHAiOjI0MTI1NzQ4MDYsImVtYWlsIjoic2FtcnRjcmVkaXRAc3VyZXBhc3MuaW8iLCJ0ZW5hbnRfaWQiOiJtYWluIiwidXNlcl9jbGFpbXMiOnsic2NvcGVzIjpbInVzZXIiXX19.KQSgpPERT6GL4P2iiJH1ZhOt4_m71Hah5cAXJdy6cnA

#----------PAYOUT----------------
payout.default.vendor.id=1


# Vimo Payout API Paths uat
vimo.api.path.token=/payoutapi/api/Signature/Authorize
vimo.api.path.banks=/masterapi/api/master/banklist
vimo.api.path.states=/masterapi/api/master/statelist
vimo.api.path.purposes=/masterapi/api/master/purposelist
vimo.api.path.payout=/payoutapi/api/Payment/payout



#-----------------RazorPay dets
razorpay.notification.secret=XDwkkY4qtj4jB7BcpCYQv0I+Bz6IfDMaDKvYMIQcBeg=

razorpay.webhook.secret = cWG6NiVZGW87rkM92pr5us77


#-------------------- Mosambee Dets

mosambee.salt = XDwkkY4qtj4jB7BcpCYQv0I